# Generated by Django 4.2.4 on 2024-05-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('name', models.TextField()),
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('salary', models.IntegerField()),
                ('design', models.TextField()),
                ('gender', models.TextField()),
                ('pan_no', models.CharField(max_length=20)),
                ('aadhar_no', models.BigIntegerField()),
                ('dateofbirth', models.TextField()),
                ('dateofjoining', models.TextField()),
                ('bankname', models.CharField(max_length=100)),
                ('ac_no', models.BigIntegerField()),
                ('uan_no', models.CharField(max_length=20)),
            ],
        ),
    ]
