# Generated by Django 5.0.6 on 2024-06-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='year',
            field=models.TextField(default=2024),
            preserve_default=False,
        ),
    ]
