# Generated by Django 5.0.6 on 2024-06-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_database_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='year',
        ),
    ]
